points:
  zones:
    matrix:
      key:
        padding: &short 17
      columns:
        pinky:
          rows:
            top:
              shift: [-16.5, -23]
              bind: [0, 0, 5, 0]
            home:
              shift: [0.5, 0]
              bind: [0, 0, 5, 0]
            bottom:
              shift: [0.5, 0]
              bind: [0, 5, 0, 0]
          key:
            padding: &long 18
            rotate: 90
            column_net: P20
            mirror:
              column_net: P3
        ring:
          spread: *long
          stagger: 7
          rows:
            top:
              bind: [0, 5, 5, 0]
            home:
              bind: [0, 5, 5, 0]
            bottom:
              bind: [0, 0, 0, 5]
          key:
            column_net: P19
            mirror:
              column_net: P4
        middle:
          spread: *long
          stagger: 7
          rows:
            top:
              bind: [0, 0, 5, 0]
            home:
              bind: [0, 0, 5, 0]
            bottom:
              bind: [0, 5, 0, 5]
          key:
            column_net: P18
            mirror:
              column_net: P5
        index:
          spread: *long
          stagger: -7
          rows:
            top:
              bind: [0, 0, 5, 5]
            home:
              bind: [0, 0, 5, 5]
          key:
            column_net: P15
            mirror:
              column_net: P6
        inner:
          spread: *long
          rows:
            top:
              bind: [0, 0, 5, 5]
            home:
              bind: [0, 0, 5, 5]
            bottom:
              bind: [0, 0, 0, 5]
          key:
            column_net: P14
            mirror:
              column_net: P7
      rows:
        bottom:
          row_net: P8
        home:
          row_net: P21
        top:
          row_net: P2
    switch_footprints:
      extends: matrix
      columns:
        pinky:
          rows:
        ring:
        middle:
        index:
        inner:
      key:
        padding: *short
        footprints: &footprints
          choc:
            type: choc
            nets:
              from: '!colrow'
              to: '!column_net'
          diode:
            type: diode
            anchor:
              # Kailh PG1350 data sheet says 4.7 mm from center of post to center of LED hole
              shift: [0, -4.7]
            nets:
              from: '!colrow'
              to: '!row_net'
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [6, -17.5]
      columns:
        nearer:
          rows:
            thumb:
              bind: [0, 5, 0, 0]
              column_net: P19
              mirror:
                column_net: P4
        near:
          spread: *short
          rows:
            thumb:
              column_net: P18
              mirror:
                column_net: P5
        home:
          spread: *short
          rows:
            thumb:
              column_net: P15
              mirror:
                column_net: P6
        far:
          spread: *short
          rows:
            thumb:
              bind: [0, 5, 0, 0]
              shift: [-5, -18]
              column_net: P14
              mirror:
                column_net: P7
      rows:
        thumb:
          row_net: P16
      key:
        rotate: 90
        padding: *short
        footprints: *footprints
  rotate: -25
  mirror:
    ref: matrix_inner_top
    shift: [6.85, 6.85]
    distance: 11 # Just enough for mini-USB-to-USB-C adapater to pass
outlines:
  glue:
    default:
      top:
        left:
          ref: matrix_inner_top
          shift: [0.5, 0.5]
        right:
          ref: mirror_matrix_inner_top
          shift: [0.5, 0.5]
      bottom:
        left:
          ref: thumbfan_nearer_thumb
          shift: [-0.5, 0.4]
          rotate: 90
        right:
          ref: mirror_thumbfan_nearer_thumb
          shift: [-0.5, 0.4]
          rotate: -90
  exports:
    _notch:
      - type: rectangle
        ref:
          - matrix_inner_top
          - mirror_matrix_inner_top
        size: [11, 20]
        shift: [-5.5, -15]
        corner: &corner 1
    _window:
      - type: rectangle
        ref:
          - matrix_inner_bottom
          - mirror_matrix_inner_bottom
        size: [11, 26]
        shift: [-5.5, -13.5]
        corner: *corner
    _perforations:
      - type: rectangle
        ref: matrix_pinky_top
        shift: [-5, -10.15]
        size: [10, 2]
        corner: 1
      - type: rectangle
        ref: mirror_matrix_pinky_top
        shift: [5, -10.15]
        size: [10, 2]
        corner: 1
      - type: rectangle
        ref: thumbfan_far_thumb
        rotate: 90
        shift: [11.15, -5]
        size: [10, 2]
        corner: 1
      - type: rectangle
        ref: mirror_thumbfan_far_thumb
        rotate: -90
        shift: [11.15, 5]
        size: [10, 2]
        corner: 1
    _pcb_edge:
      - operation: add
        type: keys
        side: both
        size: [13.7, 13.7] # Choc footprint
      - operation: subtract
        type: outline
        name: _notch
      - operation: subtract
        type: outline
        name: _window
      - operation: subtract
        type: outline
        name: _perforations
    mockup:
      - operation: add
        type: outline
        name: _pcb_edge
      - operation: stack
        type: keys
        side: both
        size: [17.5, 16.5] # MBK keycap
        bound: false
pcbs:
  main:
    outlines:
      main:
        outline: _pcb_edge
    footprints:
      mcu:
        type: promicro
        anchor:
          ref:
            - matrix_inner_bottom
            - mirror_matrix_inner_bottom
          rotate: 270
          shift: [0, -1]
      reset:
        type: reset
        params:
          side: F
        nets:
          from: RST
          to: GND
        anchor:
          ref:
            - thumbfan_home_thumb
            - mirror_thumbfan_home_thumb
          shift: [0, -5]
